[2024-04-02T11:12:51.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T11:12:51.635+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T11:12:51.637+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-04-02T11:12:51.660+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): STT> on 2024-04-01 00:00:00+00:00
[2024-04-02T11:12:51.668+0000] {standard_task_runner.py:57} INFO - Started process 56 to run task
[2024-04-02T11:12:51.681+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stt_task', 'STT', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpb3itf6o3']
[2024-04-02T11:12:51.693+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask STT
[2024-04-02T11:12:51.806+0000] {task_command.py:416} INFO - Running <TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [running]> on host bd3757cb365e
[2024-04-02T11:12:52.143+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stt_task' AIRFLOW_CTX_TASK_ID='STT' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-04-02T11:12:52.147+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task.py", line 58, in STT
    to_db(df)
UnboundLocalError: local variable 'df' referenced before assignment
[2024-04-02T11:12:52.159+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stt_task, task_id=STT, execution_date=20240401T000000, start_date=20240402T111251, end_date=20240402T111252
[2024-04-02T11:12:52.178+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task STT (local variable 'df' referenced before assignment; 56)
[2024-04-02T11:12:52.216+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-02T11:12:52.243+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T13:10:10.772+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T13:10:10.793+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T13:10:10.797+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-04-02T13:10:10.828+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): STT> on 2024-04-01 00:00:00+00:00
[2024-04-02T13:10:10.843+0000] {standard_task_runner.py:57} INFO - Started process 1565 to run task
[2024-04-02T13:10:10.850+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stt_task', 'STT', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpqlc1q6d0']
[2024-04-02T13:10:10.858+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask STT
[2024-04-02T13:10:11.091+0000] {task_command.py:416} INFO - Running <TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [running]> on host bd3757cb365e
[2024-04-02T13:10:11.302+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stt_task' AIRFLOW_CTX_TASK_ID='STT' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-04-02T13:10:11.307+0000] {logging_mixin.py:154} INFO - b'{"language": "ko-KR", "completion": "sync", "callback": null, "userdata": null, "wordAlignment": true, "fullText": true, "forbiddens": null, "boostings": null, "diarization": null}'
[2024-04-02T13:10:26.278+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-04-02T13:10:26.297+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=stt_task, task_id=STT, execution_date=20240401T000000, start_date=20240402T131010, end_date=20240402T131026
[2024-04-02T13:10:26.361+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-04-02T13:10:26.380+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T14:07:16.880+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T14:07:16.903+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T14:07:16.904+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-04-02T14:07:16.933+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): STT> on 2024-04-01 00:00:00+00:00
[2024-04-02T14:07:16.940+0000] {standard_task_runner.py:57} INFO - Started process 2281 to run task
[2024-04-02T14:07:16.944+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stt_task', 'STT', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpyc3oogam']
[2024-04-02T14:07:16.952+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask STT
[2024-04-02T14:07:17.039+0000] {task_command.py:416} INFO - Running <TaskInstance: stt_task.STT scheduled__2024-04-01T00:00:00+00:00 [running]> on host bd3757cb365e
[2024-04-02T14:07:17.168+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stt_task' AIRFLOW_CTX_TASK_ID='STT' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-04-02T14:07:17.174+0000] {logging_mixin.py:154} INFO - b'{"language": "ko-KR", "completion": "sync", "callback": null, "userdata": null, "wordAlignment": true, "fullText": true, "forbiddens": null, "boostings": null, "diarization": null}'
[2024-04-02T14:07:31.689+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-04-02T14:07:31.713+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=stt_task, task_id=STT, execution_date=20240401T000000, start_date=20240402T140716, end_date=20240402T140731
[2024-04-02T14:07:31.782+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-04-02T14:07:31.802+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
